spring.application.name=classicamoveis-envia-mensagem-ms

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
rabbitmq.queue.name=mensagens-estoque

# Telegram Bot API
# Crie um bot com o @BotFather e informe o token abaixo.
# O chat ID é obtido após enviar /start para o bot e consultar getUpdates.
telegram.bot.token=8678941590:AAEd0Lvz19EAQ_-kL9BkEMbkkeQ1917dev4
telegram.chat.id=1247804421
telegram.scheduler.delay=180000

server.port=8081
